TB-5357 - Add infinite scroll to the section overview page for courses
goalgorilla/social_course pull request #35
Opened 2021-02-04 11:43 UTC by sjoerdvandervis

### HTT

* Checkout this branch and add a course with more then 10 sections;
* See that you get the load more which loads the next sections with Ajax.

2021-02-04 13:32 UTC, navneet0693 requested changes

2021-02-04 13:32 UTC, navneet0693 commented on social_course.install
> +}
New line!

2021-02-04 13:32 UTC, navneet0693 commented on config/install/views.view.course.yml
> +    - views_infinite_scroll
It's a good idea to add dependency here: https://github.com/goalgorilla/social_course/blob/8.x-2.x/social_course.info.yml and https://github.com/goalgorilla/social_course/blob/8.x-2.x/composer.json

2021-02-05 10:20 UTC, sjoerdvandervis commented on config/install/views.view.course.yml
> +    - views_infinite_scroll
Added!

2021-02-05 10:20 UTC, sjoerdvandervis commented on social_course.install
> +}
Done!

2021-02-08 08:17 UTC, navneet0693 approved these changes

2021-02-08 08:18 UTC, navneet0693 commented
We will not be merging this until all the stakeholders agree to introduce this feature in our module.

2021-02-11 14:23 UTC, navneet0693 commented on social_course.install
> +}
New line :D

2021-04-21 13:30 UTC, ribel approved these changes
I have tested the changes and all works good, so I will include it the next release.

2021-04-21 13:39 UTC, merged