Feature/3197238
goalgorilla/social_course pull request #36
Opened 2021-02-08 12:35 UTC by rollki

2021-02-15 17:14 UTC, ribel requested changes
@rollki, In general, looks good, but please check and fix my comments.

2021-02-15 17:14 UTC, ribel commented on modules/social_course_advanced/modules/social_course_advanced_invite/config/install/group.content_type.course_advanced-group_invitation.yml
> +  invitation_body: "Hi,<br /><br /> I would like to invite you to join my group [group:title] on [site:name].<br /><br />Kind regards,<br />[current-user:display-name]<br /><br /><table class=\"btn-w
@rollki It would be better to replace `group` to `course` here and in all other places.

2021-02-15 17:14 UTC, ribel commented on modules/social_course_advanced/modules/social_course_advanced_invite/social_course_advanced_invite.info.yml
> +description: 'Extend Group Invite member feature.'
@rollki could fix the description here, so it fits to course ;)

2021-02-15 17:14 UTC, ribel commented on modules/social_course_basic/modules/social_course_basic_invite/config/install/group.content_type.course_basic-group_invitation.yml
> +  invitation_body: "Hi,<br /><br /> I would like to invite you to join my group [group:title] on [site:name].<br /><br />Kind regards,<br />[current-user:display-name]<br /><br /><table class=\"btn-w
@rollki Replace `group` with `course` here as well

2021-02-15 17:14 UTC, ribel commented on modules/social_course_basic/modules/social_course_basic_invite/social_course_basic_invite.info.yml
> +description: 'Extend Group Invite member feature.'
@rollki Fix the description here.

2021-02-16 16:23 UTC, rollki commented on modules/social_course_advanced/modules/social_course_advanced_invite/config/install/group.content_type.course_advanced-group_invitation.yml
> +  invitation_body: "Hi,<br /><br /> I would like to invite you to join my group [group:title] on [site:name].<br /><br />Kind regards,<br />[current-user:display-name]<br /><br /><table class=\"btn-w
replaced

2021-02-16 16:23 UTC, rollki commented on modules/social_course_advanced/modules/social_course_advanced_invite/social_course_advanced_invite.info.yml
> +description: 'Extend Group Invite member feature.'
fixed

2021-02-16 16:23 UTC, rollki commented on modules/social_course_basic/modules/social_course_basic_invite/config/install/group.content_type.course_basic-group_invitation.yml
> +  invitation_body: "Hi,<br /><br /> I would like to invite you to join my group [group:title] on [site:name].<br /><br />Kind regards,<br />[current-user:display-name]<br /><br /><table class=\"btn-w
replaced

2021-02-16 16:23 UTC, rollki commented on modules/social_course_basic/modules/social_course_basic_invite/social_course_basic_invite.info.yml
> +description: 'Extend Group Invite member feature.'
fixed

2021-02-17 10:26 UTC, ribel approved these changes

2021-02-25 10:10 UTC, ribel approved these changes

2021-02-25 10:11 UTC, merged