Feature/3197706
goalgorilla/social_course pull request #38
Opened 2021-02-10 14:42 UTC by rollki

2021-02-15 17:24 UTC, ribel requested changes
@rollki, In general, look good, just rename labels from group to course in string visible to the users.

2021-02-15 17:24 UTC, ribel commented on modules/social_course_basic/modules/social_course_basic_request/config/install/field.field.group.course_basic.field_group_allowed_join_method.yml
> +description: 'Choose how people can join this group.'
@rollki please rename `group` to `course` here and in all other places visible to the user.

2021-02-15 17:27 UTC, ribel commented on modules/social_course_advanced/modules/social_course_advanced_request/social_course_advanced_request.info.yml
> +name: 'Social Advanced Course Join'
@rollki rename Join to Request here to be consistent.

2021-02-16 16:15 UTC, rollki commented on modules/social_course_basic/modules/social_course_basic_request/config/install/field.field.group.course_basic.field_group_allowed_join_method.yml
> +description: 'Choose how people can join this group.'
Done.

2021-02-16 16:15 UTC, rollki commented on modules/social_course_advanced/modules/social_course_advanced_request/social_course_advanced_request.info.yml
> +name: 'Social Advanced Course Join'
Done.

2021-02-17 10:27 UTC, ribel approved these changes

2021-02-25 10:19 UTC, ribel approved these changes

2021-02-25 17:46 UTC, merged