Issue #3201809 by Ressinel: Show course statistics for Course Manager.
goalgorilla/social_course pull request #43
Opened 2021-03-05 12:54 UTC by Ressinel

## Problem

There is no way to get insight into the course statistics in terms of completion rate and where users are stuck.
We want to add more insight in this based on:

- Completion rate
- Tracking of users through the course

## Issue tracker
- https://www.drupal.org/project/social_course/issues/3201809
- https://getopensocial.atlassian.net/browse/YANG-4383

## How to test
Check the course statistics page.

2021-03-11 21:22 UTC, ribel requested changes
@Ressinel Please check and fix my comments.

2021-03-11 21:22 UTC, ribel commented on modules/social_course_statistics/config/install/core.entity_view_display.group.course_advanced.statistics.yml
> +_core:
@Ressinel we should remove those `default_config_hash` and also uuid from config files.

2021-03-11 21:22 UTC, ribel commented on modules/social_course_statistics/config/install/core.entity_view_display.group.course_basic.statistics.yml
> +_core:
@Ressinel we should remove those `default_config_hash` and also uuid from config files.

2021-03-11 21:22 UTC, ribel commented on modules/social_course_statistics/config/install/core.entity_view_display.profile.profile.statistics.yml
> +  badges:
@Ressinel Social Badge is a separate optional module. So we should remove it from here.

2021-03-11 21:22 UTC, ribel commented on modules/social_course_statistics/config/install/core.entity_view_display.profile.profile.statistics.yml
> +  field_profile_avatar: true
@Ressinel It would be better to remove all references to modules that are not in Social core, like `field_profile_avatar` for example.

2021-03-11 21:22 UTC, ribel commented on modules/social_course_statistics/src/Plugin/Block/CourseStatisticsHeroBlock.php
> +      $build['#cache']['tags'][] = 'group_block:' . $group->id();
@Ressinel I think it's better to move those cache-related things to separate methods like `getCacheTags()`

2021-03-12 05:57 UTC, Ressinel commented on modules/social_course_statistics/config/install/core.entity_view_display.group.course_advanced.statistics.yml
> +_core:
@ribel Removed.

2021-03-12 05:57 UTC, Ressinel commented on modules/social_course_statistics/config/install/core.entity_view_display.group.course_basic.statistics.yml
> +_core:
@ribel Removed.

2021-03-12 05:57 UTC, Ressinel commented on modules/social_course_statistics/config/install/core.entity_view_display.profile.profile.statistics.yml
> +  badges:
@ribel Removed.

2021-03-12 05:58 UTC, Ressinel commented on modules/social_course_statistics/config/install/core.entity_view_display.profile.profile.statistics.yml
> +  field_profile_avatar: true
@ribel Removed.

2021-03-12 05:58 UTC, Ressinel commented on modules/social_course_statistics/src/Plugin/Block/CourseStatisticsHeroBlock.php
> +      $build['#cache']['tags'][] = 'group_block:' . $group->id();
@ribel Moved to separate methods.

2021-03-12 14:46 UTC, ribel approved these changes

2021-03-12 14:48 UTC, merged